### ISSUE TITLE
Crash on entering castle courtyard

### ISSUE THREAD

**Issue by numbypad** [blawar/ooot#50]
as soon as coming out the other side of the crawl space the game crashes

**Comment by DaMarkov** [comment]
It doesn't crash for me. Did it crash during day or nighttime?
Did you use save 1 (with the debug menu) and walked there from Hyrule field or did you use one of the other save slots and played till the castle courtyard?

**Comment by numbypad** [comment]
I played on file 2, did navi dive skip to get out of the forest since gohma would crash so I couldn't beat the deku tree. then played the game normally, woke talon up with the chicken and then as soon as I crawled through to space it crashed. i tried multiple times and It crashed everytime.

**Comment by DaMarkov** [comment]
Thanks! Took me a while since I had to first learn this navi dive skip.
The game crashes because z_en_heishi.c access the `setupPathList` outside the array.
This is the same bug as in issue #40. The `setupPathList` is exported incorrectly by ZAPD.
A fix (for both of these issues) is currently being worked on.

Setting line 169 of z_en_heishi.c to `path = &globalCtx->setupPathList[0];` would let you play further (the soldiers would of course use the incorrect paths).

**Comment by Zero3K** [comment]
This should be fixed now thanks to https://github.com/blawar/ooot/commit/1fa2d716a2959223765d1ccb802f71e95110be92.

**Comment by Chewbear67** [comment]
> This should be fixed now thanks to [1fa2d71](https://github.com/blawar/ooot/commit/1fa2d716a2959223765d1ccb802f71e95110be92).

Still happening for me. Trying to do a regular playthrough on file 2 and so far only crash when entering the courtyard during the daytime as kid link

**Comment by Zero3K** [comment]
Did you re-run setup_assets.bat?

**Comment by Chewbear67** [comment]
> Did you re-run setup_assets.bat?

Nope, works now. Thanks!

**Comment by Zero3K** [comment]
You're welcome.
